### ISSUE TITLE
syntax error while creating database tables

### ISSUE THREAD

**Issue by sanjaypopcorn** [hfellerhoff/listentogether#1] opened 2021-12-05 13:42 UTC
create table songs (
    id    integer primary key NOT NULL ,
    room_id integer NOT NULL , 
    spotifyUri  varchar NOT NULL ,
    progress bigint NOT NULL DEFAULT 0 ,
    isPaused boolean NOT NULL DEFAULT "true" ,
    updatedAt integer DEFAULT NOW() ,
    addedAt integer DEFAULT NOW() ,
) ;

gives: "syntax error at or near ")""

**Comment by hfellerhoff** [comment] 2021-12-05 19:38
I saw that you closed this issue - did you figure it out? I'd be happy to help if things still aren't working.

**Comment by sanjaypopcorn** [comment] 2021-12-05 20:08
it still says that, I skipped on that while I waited for a reply and there are so many errors, I just want to make it work so me and my long distance partner can listen to music together:(
Id really appretiate it if you could help me get this working

**Comment by hfellerhoff** [comment] 2021-12-05 20:23
Okay so as I understand it when you click on a room the app crashes or goes blank and "Cannot read property 'id' of undefined" is printed in the console, correct? It would be great if you could attach either a couple screenshots reproducing the issue or a screen recording, as I can't reproduce the issue on my end right now. Also, do you happen to have Spotify premium? There are some issues with the API and playing songs if you don't – it's just a limitation Spotify puts on their API.

I hope we can get this figured out!

**Comment by sanjaypopcorn** [comment] 2021-12-05 20:30
ah:( see if I had spotify premium this would be pretty pointless as they already have a group session feature. I still appretiate you making this and offering to help me. Goodluck in your endeavours hope everything works out for you.
I checked out your page and you're doing great work.
<3

**Comment by hfellerhoff** [comment] 2021-12-05 20:38
Yeah I'm really sorry, I wish I could get around it but I can't :(

It looks like this site is free since it uses YouTube, so you could give this a try: watch2gether.com. Also, it's a little more effort but I know there are tons of Discord bots you can add to a channel and use Spotify without needing someone to have premium.

Best of luck! <3

**Closed as completed** 2021-12-14 06:41 UTC
